"""
    Brasil API

    Acesso programático de informações é algo fundamental na comunicação entre sistemas mas, para nossa surpresa, uma informação tão útil e pública quanto um CEP não consegue ser acessada diretamente por um navegador por conta da API dos Correios não possuir CORS habilitado. Dado a isso, este projeto experimental tem como objetivo centralizar e disponibilizar endpoints modernos com baixíssima latência utilizando tecnologias como Vercel Smart CDN responsável por fazer o cache das informações em atualmente 23 regiões distribuídas ao longo do mundo (incluindo Brasil). Então não importa o quão devagar for a fonte dos dados, nós queremos disponibilizá-la da forma mais rápida e moderna possível.  Recursos disponíveis   - CEP   - DDD   - Banks   - CNPJ   - IBGE   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import brasil_api
from brasil_api.model.bank_v1 import BankV1


class TestBankV1(unittest.TestCase):
    """BankV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankV1(self):
        """Test BankV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
