"""
    Brasil API

    Acesso programático de informações é algo fundamental na comunicação entre sistemas mas, para nossa surpresa, uma informação tão útil e pública quanto um CEP não consegue ser acessada diretamente por um navegador por conta da API dos Correios não possuir CORS habilitado. Dado a isso, este projeto experimental tem como objetivo centralizar e disponibilizar endpoints modernos com baixíssima latência utilizando tecnologias como Vercel Smart CDN responsável por fazer o cache das informações em atualmente 23 regiões distribuídas ao longo do mundo (incluindo Brasil). Então não importa o quão devagar for a fonte dos dados, nós queremos disponibilizá-la da forma mais rápida e moderna possível.  Recursos disponíveis   - CEP   - DDD   - Banks   - CNPJ   - IBGE   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from brasil_api.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class EmpresaV1(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('cnpj',): {
            'min_length': 1,
        },
        ('descricao_matriz_filial',): {
            'min_length': 1,
        },
        ('razao_social',): {
            'min_length': 1,
        },
        ('nome_fantasia',): {
            'min_length': 1,
        },
        ('descricao_situacao_cadastral',): {
            'min_length': 1,
        },
        ('data_situacao_cadastral',): {
            'min_length': 1,
        },
        ('data_inicio_atividade',): {
            'min_length': 1,
        },
        ('cnae_fiscal_descricao',): {
            'min_length': 1,
        },
        ('descricao_tipo_logradouro',): {
            'min_length': 1,
        },
        ('logradouro',): {
            'min_length': 1,
        },
        ('numero',): {
            'min_length': 1,
        },
        ('complemento',): {
            'min_length': 1,
        },
        ('bairro',): {
            'min_length': 1,
        },
        ('uf',): {
            'min_length': 1,
        },
        ('municipio',): {
            'min_length': 1,
        },
        ('ddd_telefone_1',): {
            'min_length': 1,
        },
        ('descricao_porte',): {
            'min_length': 1,
        },
        ('cnaes_secundarios',): {
            'min_items': 1,
        },
        ('qsa',): {
            'min_items': 1,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'cnpj': (str,),  # noqa: E501
            'identificador_matriz_filial': (float,),  # noqa: E501
            'descricao_matriz_filial': (str,),  # noqa: E501
            'razao_social': (str,),  # noqa: E501
            'nome_fantasia': (str,),  # noqa: E501
            'situacao_cadastral': (float,),  # noqa: E501
            'descricao_situacao_cadastral': (str,),  # noqa: E501
            'data_situacao_cadastral': (str,),  # noqa: E501
            'motivo_situacao_cadastral': (float,),  # noqa: E501
            'codigo_natureza_juridica': (float,),  # noqa: E501
            'data_inicio_atividade': (str,),  # noqa: E501
            'cnae_fiscal': (float,),  # noqa: E501
            'cnae_fiscal_descricao': (str,),  # noqa: E501
            'descricao_tipo_logradouro': (str,),  # noqa: E501
            'logradouro': (str,),  # noqa: E501
            'numero': (str,),  # noqa: E501
            'complemento': (str,),  # noqa: E501
            'bairro': (str,),  # noqa: E501
            'cep': (float,),  # noqa: E501
            'uf': (str,),  # noqa: E501
            'codigo_municipio': (float,),  # noqa: E501
            'municipio': (str,),  # noqa: E501
            'ddd_telefone_1': (str,),  # noqa: E501
            'qualificacao_do_responsavel': (float,),  # noqa: E501
            'capital_social': (float,),  # noqa: E501
            'porte': (float,),  # noqa: E501
            'descricao_porte': (str,),  # noqa: E501
            'opcao_pelo_simples': (bool,),  # noqa: E501
            'opcao_pelo_mei': (bool,),  # noqa: E501
            'cnaes_secundarios': ([object],),  # noqa: E501
            'qsa': ([object],),  # noqa: E501
            'nome_cidade_exterior': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'ddd_telefone_2': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'ddd_fax': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'data_opcao_pelo_simples': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'data_exclusao_do_simples': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'situacao_especial': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'data_situacao_especial': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'cnpj': 'cnpj',  # noqa: E501
        'identificador_matriz_filial': 'identificador_matriz_filial',  # noqa: E501
        'descricao_matriz_filial': 'descricao_matriz_filial',  # noqa: E501
        'razao_social': 'razao_social',  # noqa: E501
        'nome_fantasia': 'nome_fantasia',  # noqa: E501
        'situacao_cadastral': 'situacao_cadastral',  # noqa: E501
        'descricao_situacao_cadastral': 'descricao_situacao_cadastral',  # noqa: E501
        'data_situacao_cadastral': 'data_situacao_cadastral',  # noqa: E501
        'motivo_situacao_cadastral': 'motivo_situacao_cadastral',  # noqa: E501
        'codigo_natureza_juridica': 'codigo_natureza_juridica',  # noqa: E501
        'data_inicio_atividade': 'data_inicio_atividade',  # noqa: E501
        'cnae_fiscal': 'cnae_fiscal',  # noqa: E501
        'cnae_fiscal_descricao': 'cnae_fiscal_descricao',  # noqa: E501
        'descricao_tipo_logradouro': 'descricao_tipo_logradouro',  # noqa: E501
        'logradouro': 'logradouro',  # noqa: E501
        'numero': 'numero',  # noqa: E501
        'complemento': 'complemento',  # noqa: E501
        'bairro': 'bairro',  # noqa: E501
        'cep': 'cep',  # noqa: E501
        'uf': 'uf',  # noqa: E501
        'codigo_municipio': 'codigo_municipio',  # noqa: E501
        'municipio': 'municipio',  # noqa: E501
        'ddd_telefone_1': 'ddd_telefone_1',  # noqa: E501
        'qualificacao_do_responsavel': 'qualificacao_do_responsavel',  # noqa: E501
        'capital_social': 'capital_social',  # noqa: E501
        'porte': 'porte',  # noqa: E501
        'descricao_porte': 'descricao_porte',  # noqa: E501
        'opcao_pelo_simples': 'opcao_pelo_simples',  # noqa: E501
        'opcao_pelo_mei': 'opcao_pelo_mei',  # noqa: E501
        'cnaes_secundarios': 'cnaes_secundarios',  # noqa: E501
        'qsa': 'qsa',  # noqa: E501
        'nome_cidade_exterior': 'nome_cidade_exterior',  # noqa: E501
        'ddd_telefone_2': 'ddd_telefone_2',  # noqa: E501
        'ddd_fax': 'ddd_fax',  # noqa: E501
        'data_opcao_pelo_simples': 'data_opcao_pelo_simples',  # noqa: E501
        'data_exclusao_do_simples': 'data_exclusao_do_simples',  # noqa: E501
        'situacao_especial': 'situacao_especial',  # noqa: E501
        'data_situacao_especial': 'data_situacao_especial',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, cnpj, identificador_matriz_filial, descricao_matriz_filial, razao_social, nome_fantasia, situacao_cadastral, descricao_situacao_cadastral, data_situacao_cadastral, motivo_situacao_cadastral, codigo_natureza_juridica, data_inicio_atividade, cnae_fiscal, cnae_fiscal_descricao, descricao_tipo_logradouro, logradouro, numero, complemento, bairro, cep, uf, codigo_municipio, municipio, ddd_telefone_1, qualificacao_do_responsavel, capital_social, porte, descricao_porte, opcao_pelo_simples, opcao_pelo_mei, cnaes_secundarios, qsa, *args, **kwargs):  # noqa: E501
        """EmpresaV1 - a model defined in OpenAPI

        Args:
            cnpj (str):
            identificador_matriz_filial (float):
            descricao_matriz_filial (str):
            razao_social (str):
            nome_fantasia (str):
            situacao_cadastral (float):
            descricao_situacao_cadastral (str):
            data_situacao_cadastral (str):
            motivo_situacao_cadastral (float):
            codigo_natureza_juridica (float):
            data_inicio_atividade (str):
            cnae_fiscal (float):
            cnae_fiscal_descricao (str):
            descricao_tipo_logradouro (str):
            logradouro (str):
            numero (str):
            complemento (str):
            bairro (str):
            cep (float):
            uf (str):
            codigo_municipio (float):
            municipio (str):
            ddd_telefone_1 (str):
            qualificacao_do_responsavel (float):
            capital_social (float):
            porte (float):
            descricao_porte (str):
            opcao_pelo_simples (bool):
            opcao_pelo_mei (bool):
            cnaes_secundarios ([object]):
            qsa ([object]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            nome_cidade_exterior (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            ddd_telefone_2 (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            ddd_fax (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            data_opcao_pelo_simples (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            data_exclusao_do_simples (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            situacao_especial (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            data_situacao_especial (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.cnpj = cnpj
        self.identificador_matriz_filial = identificador_matriz_filial
        self.descricao_matriz_filial = descricao_matriz_filial
        self.razao_social = razao_social
        self.nome_fantasia = nome_fantasia
        self.situacao_cadastral = situacao_cadastral
        self.descricao_situacao_cadastral = descricao_situacao_cadastral
        self.data_situacao_cadastral = data_situacao_cadastral
        self.motivo_situacao_cadastral = motivo_situacao_cadastral
        self.codigo_natureza_juridica = codigo_natureza_juridica
        self.data_inicio_atividade = data_inicio_atividade
        self.cnae_fiscal = cnae_fiscal
        self.cnae_fiscal_descricao = cnae_fiscal_descricao
        self.descricao_tipo_logradouro = descricao_tipo_logradouro
        self.logradouro = logradouro
        self.numero = numero
        self.complemento = complemento
        self.bairro = bairro
        self.cep = cep
        self.uf = uf
        self.codigo_municipio = codigo_municipio
        self.municipio = municipio
        self.ddd_telefone_1 = ddd_telefone_1
        self.qualificacao_do_responsavel = qualificacao_do_responsavel
        self.capital_social = capital_social
        self.porte = porte
        self.descricao_porte = descricao_porte
        self.opcao_pelo_simples = opcao_pelo_simples
        self.opcao_pelo_mei = opcao_pelo_mei
        self.cnaes_secundarios = cnaes_secundarios
        self.qsa = qsa
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
