# flake8: noqa

"""
    Brasil API

    Acesso programático de informações é algo fundamental na comunicação entre sistemas mas, para nossa surpresa, uma informação tão útil e pública quanto um CEP não consegue ser acessada diretamente por um navegador por conta da API dos Correios não possuir CORS habilitado. Dado a isso, este projeto experimental tem como objetivo centralizar e disponibilizar endpoints modernos com baixíssima latência utilizando tecnologias como Vercel Smart CDN responsável por fazer o cache das informações em atualmente 23 regiões distribuídas ao longo do mundo (incluindo Brasil). Então não importa o quão devagar for a fonte dos dados, nós queremos disponibilizá-la da forma mais rápida e moderna possível.  Recursos disponíveis   - CEP   - DDD   - Banks   - CNPJ   - IBGE   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from brasil_api.api_client import ApiClient

# import Configuration
from brasil_api.configuration import Configuration

# import exceptions
from brasil_api.exceptions import OpenApiException
from brasil_api.exceptions import ApiAttributeError
from brasil_api.exceptions import ApiTypeError
from brasil_api.exceptions import ApiValueError
from brasil_api.exceptions import ApiKeyError
from brasil_api.exceptions import ApiException
